title: EditData
description: "Collaboratively manage data."
permalink: /posts/:title
baseurl: ''
exclude: [node_modules, tmp, bin, css]

collections:
  contributors:
    output: true
    permalink: /:path/
  packages:
    output: true
    permalink: /packages/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "contributors"
    values:
      layout: "contributor"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  -
    scope:
      path: ""
      type: "packages"
    values:
      layout: "package"