title: EditData
description: "Collaboratively manage data."
permalink: /posts/:title
baseurl: ''
markdown: redcarpet
exclude: [node_modules, tmp, bin, css]

collections:
  contributors:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
